Ea 2835 change disabled fields to date
europeana/annotation pull request #294
Opened 2021-12-01 19:06 UTC by SrdjanStevanetic

2021-12-07 12:01 UTC, gsergiu requested changes
there are a few method signatures to be improved and some improvement needed for exception handling

2021-12-07 17:30 UTC, SrdjanStevanetic commented on annotation-web/src/main/java/eu/europeana/annotation/web/service/AnnotationService.java
> +	public Annotation getAnnotationById(AnnotationId annoId, String userId, boolean enabled) throws AnnotationNotFoundException, UserAuthorizationException;
Please note that this method is called also when we need to get the disabled annotations, e.g. in the verifyOwnerOrAdmin method during enabling the annotations. So we can use the same method with the parameter.

2021-12-07 17:30 UTC, SrdjanStevanetic commented on annotation-mongo/src/main/java/eu/europeana/annotation/mongo/service/PersistentAnnotationServiceImpl.java
> +		updateOperations.set(WebAnnotationFields.DISABLED, persistentAnnotation.getDisabled());
Makes sense.

2021-12-07 17:31 UTC, SrdjanStevanetic commented on annotation-mongo/src/main/java/eu/europeana/annotation/mongo/service/PersistentAnnotationServiceImpl.java
> +			query.filter(PersistentAnnotation.FIELD_DISABLED, null);
This can even be private.

2021-12-07 17:31 UTC, SrdjanStevanetic commented on annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/BaseAnnotationServiceImpl.java
> +    public void checkPrivacy(Annotation annotation, String user) throws AnnotationStateException {
Yes, improved.

2021-12-07 17:31 UTC, SrdjanStevanetic commented on annotation-web/src/main/java/eu/europeana/annotation/web/service/impl/BaseAnnotationServiceImpl.java
> +    public void checkVisibility(Annotation annotation) throws AnnotationStateException {
Yes.

2021-12-07 17:32 UTC, SrdjanStevanetic commented on annotation-mongo/src/main/java/eu/europeana/annotation/mongo/service/PersistentAnnotationServiceImpl.java
> +    public List<AnnotationDeletion> getDeletedByTimestamp(String motivation, String startTimestamp) {
Done.

2021-12-09 11:09 UTC, SrdjanStevanetic commented on annotation-mongo/src/main/java/eu/europeana/annotation/mongo/service/PersistentAnnotationServiceImpl.java
> +    public List<AnnotationDeletion> getDeletedByTimestamp(String motivation, String startTimestamp) {
Done.

2021-12-10 08:50 UTC, merged